currLabel: Schemas
customIcon: null
enabled: true
handle: schemas
icon: null
layout: 1e06c5fa-d04f-4336-afaf-b5c8f8f1094d # Default
level: 2
newWindow: false
parent: d85a5c30-d1b4-4f5e-a864-25b5ab4a78b7
prevLabel: Schemas
prevLevel: 2
prevParent: d85a5c30-d1b4-4f5e-a864-25b5ab4a78b7
prevUrl: graphql/schemas
sortOrder: 7
type: craft
url: graphql/schemas
